yeongpin/cursor-free-vip

cursor_register.py
cursor_register_manual.py

尽量提前打印相关信息，避免出现错误后，实际上已经注册用户成功但但找不到用户/密码信息

print account info as early as possible

---

github_cursor_register.py
totally_reset_cursor.py

🚀 ✅ Changelog:
1. totally_reset_cursor.py:
Enhanced Machine ID reset → Added support for Linux, Windows, and macOS.
Expanded file coverage → Added detection for newer Cursor AI files and folders.
Improved cleanup → Added deep removal of leftover trial detection files.
Optimized logging → Clear console messages with verification steps.
2. github_cursor_register.py:
GitHub & Cursor Automation → Automated GitHub registration with temp mail API.
Cursor AI Registration → Automatic login with GitHub OAuth.
Machine ID Reset → Bypasses Cursor’s free trial detection post-registration.
Retry Mechanism → Added retries for email verification.
Logging & Credentials → Saves registered GitHub accounts and timestamps.

✨ Major Enhancements: Improved Cursor AI Reset & Automated GitHub + Cursor Registration

---

github_cursor_register.py
totally_reset_cursor.py

This pull request enhances two scripts: the **Cursor AI reset script** and the **GitHub + Cursor AI registration automation script**. The updates introduce **user confirmation**, improve reliability with better **error handling**, add detailed **logging**, and provide clear **feature/warning information** to ensure a safer and more user-friendly experience. These changes make the scripts more **robust**, **maintainable**, and aligned with **best practices**.
**Changelog**:
- **User Confirmation**:
- Added ``get_user_confirmation()`` to prompt users with a `"yes/no"` question before proceeding, preventing unintended execution.
- Integrated into ``main()`` to ensure confirmation is required before any actions are taken.
- **Features and Warnings**:
- Introduced …

Comprehensive Enhancements to Cursor AI Reset and Registration Automation Scripts

---

reset_machine_manual.py

This PR improves Linux path detection and config handling by:
1. Adding multiple default paths for Linux installations:
- `/opt/Cursor/resources/app`
- `/usr/share/cursor/resources/app`
- `~/.local/share/cursor/resources/app`
2. Adding automatic config file creation and management:
- Creates config directory if missing
- Creates config file with default paths if missing
- Updates config with found paths automatically
3. Improving path detection:
- Tries multiple common installation locations
- Automatically detects and uses the correct path
- Updates config file with the correct path for future use
This should resolve the 'path_not_found' error on Ubuntu and other Linux distributions.
Fixes #337

fix: Improve Linux path detection and config handling

---

logo.py

Change language option number is currently on 8 but the info text in logo is 7.

fix: modified the change language option number

---

logo.py

fix: inconsistent UI message

---

totally_reset_cursor.py

Update totally_reset_cursor.py face 1 wait for face 3

---

config.py

This PR improves path handling and permission checks on Linux systems, fixing issue #435.
Changes made:
1. Added proper handling for sudo vs normal user cases
2. Added case-insensitive directory detection (Cursor/cursor)
3. Added detailed permission checks and error messages
4. Added proper file existence verification
5. Added better error handling for file corruption
6. Added clear instructions for fixing permission issues
The code will now:
- Properly detect the user's home directory whether running with sudo or not
- Handle both "Cursor" and "cursor" directory names
- Verify file permissions and provide clear error messages
- Check for file corruption and provide helpful suggestions
- Show detailed error messages with specific instructions for fixing issues
This should resolve the …

fix: improve Linux path handling and fix permission issues

---

oauth_auth.py

- Add support for detecting both 150/150 and 50/50 usage limits
- Improve usage parsing and validation

fix: improve account usage limit detection

---

reset_machine_manual.py

add /usr/lib/cursor/app/ folder to patch the error: 
`❌ Reset Process Error: Linux Path Not Found`

Patch Linux Path Not Found

---

locales/bg.json
locales/de.json
locales/en.json
locales/es.json
locales/fr.json
locales/nl.json
locales/pt.json
locales/ru.json
locales/tr.json
locales/vi.json
locales/zh_cn.json
locales/zh_tw.json
main.py
oauth_auth.py

This PR adds support for selecting specific Chrome profiles when using the application. It enhances user experience by displaying actual profile names and adds safety measures when handling Chrome processes.
Closes #454 - Add an option to choose chrome profile
- ✨ Added menu option to select Chrome profiles
- 📝 Display actual profile names instead of generic "Profile X"
- ⚠️ Added safety warning before closing Chrome processes
- 🌐 Added translations for all supported languages
- 👥 Support for multiple Chrome profiles
- Read Chrome's `Local State` file to get actual profile names
- Added profile selection logic in `oauth_auth.py`
- Updated main menu to include profile selection option
- Added confirmation prompt before closing Chrome processes
- Added translations for all profile-related …

feat(oauth): add Chrome profile selection feature

---

reset_machine_manual.py

- Modify base_path detection to use custom paths from config
- Replace forward slashes with backslashes in Windows path definition

feat: Add support for custom Cursor installation paths on Windows

---

config.py
disable_auto_update.py
locales/en.json
locales/zh_cn.json
locales/zh_tw.json

Fix `Modify File Failed: RawConfigParser.get() missing 1 required positional argument: 'option'` error in disable cursor auto update.
Related issues: #482 #438

Fix: bug in disable cursor auto update

---

logo.py
oauth_auth.py

This PR addresses two main issues in the Cursor Pro Version Activator:
1. **Usage Limits Check Enhancement**
- Previously, the code only checked for exact matches of "50/50" or "150/150"
- Now it properly handles cases where usage exceeds limits (e.g., "51/50" or "151/150")
- Added better error handling for usage text parsing
2. **Tuple Index Error Fix**
- Fixed the error "tuple indices must be integers or slices, not str"
- Added proper validation before accessing usage text properties
- Improved error handling when parsing usage information
- Added new `check_usage_limits` helper function to handle usage validation
- Improved usage text parsing with proper error handling
- Added validation to prevent tuple index errors
- Updated account deletion logic to work with exceeded limits
The …

Fix: Improve usage limits check and tuple index error

---

build.spec
oauth_auth.py
utils.py

This commit fixes that error when you had an custom chrome installation. There's a bug when you have a custom or portable chrome installation. Script does not detect it even if it is added to PATH.
This commit forces script to use windows PATH to start chrome and if there's no PATH installation script would check default location.
Here's demo for current bug: https://youtu.be/O8lPblnBIGQ

[Windows] Fix for custom Chrome Installations

---

.github/workflows/build.yml
main.py

- refactor: 使用 match-case 重构语言映射和菜单选择逻辑，使代码更清晰、可维护性更高。
- ci: 更新 ARM64 Docker 构建容器中的 Python 版本至 3.10，兼容性更强，方便未来迁移。
请审阅并合并至主分支。

refactor: 优化语言逻辑 + 升级 Linux arm64 Docker Python 版本至 3.10

---

.SRCINFO
PKGBUILD

[check](https://github.com/yeongpin/cursor-free-vip/pull/630#issuecomment-2801699741)

sync(aur): 1.9.05

---

cursor_register_manual.py
requirements.txt

Introduced the Faker library in the CursorRegistration class to generate random account information, replacing the original random name generation logic.
Also updated the password generation method to use Faker for creating more complex passwords. Additionally, updated requirements.txt to include the Faker dependency.

refactor: Account Generation with Faker and Update requirements.txt

---

README.md

本次 PR 更新了 README.md，补充了 [TempMailPlus] 配置说明，包括：
•	enabled：是否启用 TempMailPlus 功能
•	email：用于接收验证码的 TempMailPlus 邮箱地址
•	epin：可选的 PIN 码，用于访问邮箱

在 README.md 中新增 TempMailPlus 配置项说明

---

account_manager.py
cursor_register_manual.py
locales/en.json
locales/zh_cn.json
locales/zh_tw.json

本次 PR 主要改进了账户管理与邮箱输入体验，具体内容如下：
•	✨ 新增 AccountManager 类，负责保存账户信息（邮箱、密码、Token、使用量）；
•	✨ 实现邮箱推荐功能：在用户输入邮箱时，自动推荐上次使用的邮箱域名 + 名字拼接后的地址（如 john.doe@yourdomain.com）；
•	🔄 CursorRegistration 类已重构，使用 AccountManager 管理账户信息与推荐邮箱逻辑；
•	🌍 更新了 zh_cn.json、zh_tw.json 和 en.json 多语言文件，支持相关提示文本的本地化。

新增 AccountManager 类，支持推荐邮箱及账户信息统一保存

---

email_tabs/tempmail_plus_tab.py

https://github.com/yeongpin/cursor-free-vip/issues/878

增强TempMailPlusTab类，添加轮询功能以检查新邮件，支持自定义轮询间隔和最大尝试次数

---

scripts/install.ps1

This pull request refactors the `Install-CursorFreeVIP` function in `scripts/install.ps1` to replace the use of `WebClient` with `HttpWebRequest` for downloading files. The new implementation improves performance and reliability by using chunked downloads and a real-time progress bar.
* Replaced `WebClient` with `HttpWebRequest` for file downloads, allowing chunked downloads and better control over the download process.
* Added a real-time progress bar using `Write-Progress`, displaying download progress, speed, and total file size in a more user-friendly format.
* Ensured the downloaded file is checked for existence and non-zero size before proceeding, throwing an error if the download fails.
* Updated the cleanup process to properly close streams (`responseStream` and `fileStream`) in a …

修復 install.ps1 下載狀態條的問題
